keywords = [
	"paul graham",
	"disruption",
	"innovation",
	"tech crunch",
	"pando daily",
	"robots",
	"trending",
	"summit series",
	"powder mountain",
	"rethink",
	"aim",
	"entrepreneurship",
	"arts",
	"relationships",
	"altruism",
//	"change",
	"change agent",
	"changemakers",
//	"new",
	"catalyze",
//	"community",
	"achievement",
	"personal growth",
	"culture",
	"unknown",
	"core competency",
	"buy-in",
	"social entrepreneurship",
	"monetize",
	"commoditize",
	"network theorist",
	"partnership",
	"global community",
	"member engagement",
	"brand loyalty",
//	"content",
	"resilience",
	"building capabilities",
	"customer base",
	"swim lane",
	"empower",
	"drinking the kool aid",
	"move the needle",
	"open the kimono",
	"bleeding edge",
	"tiger teams",
	"moving parts",
	"core values",
	"mission",
	"scalable",
	"best practices",
	"think outside the box",
	"ducks in a row",
	"at the end of the day",
	"ecosystem",
	"solution",
	"leverage",
	"vertical",
	"robust",
	"hard stop",
	"impact",
	"body of work",
	"price point",
	"window of opportunity",
	"low hanging fruit",
	"going forward"
]
